Repository cvs-go/cvs-go-server, pull requests merged in 2023-03, with the labels that each got.

#15 로그인 기능 추가
  build.gradle
  src/docs/api-doc.adoc
  src/main/java/com/cvsgo/argumentresolver/LoginUser.java
  src/main/java/com/cvsgo/argumentresolver/LoginUserArgumentResolver.java
  src/main/java/com/cvsgo/config/WebConfig.java
  src/main/java/com/cvsgo/controller/AuthController.java
  src/main/java/com/cvsgo/dto/auth/LoginRequestDto.java
  src/main/java/com/cvsgo/dto/auth/LogoutRequestDto.java
  src/main/java/com/cvsgo/dto/auth/TokenDto.java
  src/main/java/com/cvsgo/entity/RefreshToken.java
  src/main/java/com/cvsgo/entity/User.java
  src/main/java/com/cvsgo/exception/ErrorCode.java
  src/main/java/com/cvsgo/exception/ExceptionConstants.java
  src/main/java/com/cvsgo/exception/GlobalExceptionHandler.java
  src/main/java/com/cvsgo/exception/auth/AuthExceptionHandler.java
  src/main/java/com/cvsgo/exception/auth/InvalidPasswordException.java
  src/main/java/com/cvsgo/exception/auth/NotFoundUserException.java
  src/main/java/com/cvsgo/exception/auth/UnauthorizedUserException.java
  src/main/java/com/cvsgo/interceptor/AuthInterceptor.java
  src/main/java/com/cvsgo/repository/RefreshTokenRepository.java
  src/main/java/com/cvsgo/service/AuthService.java
  src/main/java/com/cvsgo/util/AuthConstants.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/static/index.html
  src/test/java/com/cvsgo/controller/AuthControllerTest.java
  src/test/java/com/cvsgo/service/AuthServiceTest.java
  src/test/resources/application.yml
Labels: feature

#18 로그인/회원가입 리팩토링
  src/docs/api-doc.adoc
  src/main/java/com/cvsgo/config/WebConfig.java
  src/main/java/com/cvsgo/controller/AuthController.java
  src/main/java/com/cvsgo/controller/TagController.java
  src/main/java/com/cvsgo/controller/UserController.java
  src/main/java/com/cvsgo/dto/ErrorResponse.java
  src/main/java/com/cvsgo/dto/SuccessResponse.java
  src/main/java/com/cvsgo/dto/tag/TagResponseDto.java
  src/main/java/com/cvsgo/dto/user/SignUpRequestDto.java
  src/main/java/com/cvsgo/dto/user/SignUpResponseDto.java
  src/main/java/com/cvsgo/entity/User.java
  src/main/java/com/cvsgo/exception/GlobalExceptionHandler.java
  src/main/java/com/cvsgo/repository/UserTagRepository.java
  src/main/java/com/cvsgo/service/AuthService.java
  src/main/java/com/cvsgo/service/TagService.java
  src/main/java/com/cvsgo/service/UserService.java
  src/main/java/com/cvsgo/util/AuthConstants.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/static/index.html
  src/test/java/com/cvsgo/ApiDocumentUtils.java
  src/test/java/com/cvsgo/CvsGoServerApplicationTests.java
  src/test/java/com/cvsgo/controller/AuthControllerTest.java
  src/test/java/com/cvsgo/controller/TagControllerTest.java
  src/test/java/com/cvsgo/controller/UserControllerTest.java
  src/test/java/com/cvsgo/repository/UserRepositoryTest.java
  src/test/java/com/cvsgo/repository/UserTagRepositoryTest.java
  src/test/java/com/cvsgo/service/TagServiceTest.java
  src/test/java/com/cvsgo/service/UserServiceTest.java
Labels: refactor

#26 리뷰 작성 기능 추가
  build.gradle
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/cvsgo/config/S3Config.java
  src/main/java/com/cvsgo/controller/ReviewController.java
  src/main/java/com/cvsgo/dto/review/CreateReviewRequestDto.java
  src/main/java/com/cvsgo/entity/Review.java
  src/main/java/com/cvsgo/exception/ErrorCode.java
  src/main/java/com/cvsgo/exception/ExceptionConstants.java
  src/main/java/com/cvsgo/exception/GlobalExceptionHandler.java
  src/main/java/com/cvsgo/exception/product/NotFoundProductException.java
  src/main/java/com/cvsgo/exception/product/ProductExceptionHandler.java
  src/main/java/com/cvsgo/exception/review/ReviewExceptionHandler.java
  src/main/java/com/cvsgo/service/FileUploadService.java
  src/main/java/com/cvsgo/service/ReviewService.java
  src/main/java/com/cvsgo/service/S3FileUploadService.java
  src/main/java/com/cvsgo/util/FileConstants.java
  src/main/java/com/cvsgo/util/FileUtils.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/cvsgo/controller/ReviewControllerTest.java
  src/test/java/com/cvsgo/service/ReviewServiceTest.java
Labels: feature

#27 상품 상세 조회 기능 추가
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/cvsgo/controller/ProductController.java
  src/main/java/com/cvsgo/dto/product/ProductDetailResponseDto.java
  src/main/java/com/cvsgo/dto/product/SellAtEventResponseDto.java
  src/main/java/com/cvsgo/dto/review/CreateReviewRequestDto.java
  src/main/java/com/cvsgo/entity/Event.java
  src/main/java/com/cvsgo/entity/Product.java
  src/main/java/com/cvsgo/repository/ProductCustomRepository.java
  src/main/java/com/cvsgo/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/cvsgo/service/ProductService.java
  src/main/java/com/cvsgo/service/ReviewService.java
  src/test/java/com/cvsgo/controller/ProductControllerTest.java
  src/test/java/com/cvsgo/service/ProductServiceTest.java
Labels: feature

#31 상품 조회 쿼리 개선
  build.gradle
  src/main/java/com/cvsgo/config/WebConfig.java
  src/main/java/com/cvsgo/controller/ProductController.java
  src/main/java/com/cvsgo/dto/product/ConvenienceStoreEventQueryDto.java
  src/main/java/com/cvsgo/dto/product/ProductResponseDto.java
  src/main/java/com/cvsgo/dto/product/SearchProductQueryDto.java
  src/main/java/com/cvsgo/dto/product/SellAtResponseDto.java
  src/main/java/com/cvsgo/repository/ProductCustomRepository.java
  src/main/java/com/cvsgo/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/cvsgo/service/ProductService.java
  src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/spy.properties
  src/test/java/com/cvsgo/controller/ProductControllerTest.java
  src/test/java/com/cvsgo/service/ProductServiceTest.java
Labels: refactor

#29 상품 좋아요 생성 / 삭제 기능 추가
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/cvsgo/controller/ProductController.java
  src/main/java/com/cvsgo/entity/Product.java
  src/main/java/com/cvsgo/entity/ProductLike.java
  src/main/java/com/cvsgo/exception/ErrorCode.java
  src/main/java/com/cvsgo/exception/ExceptionConstants.java
  src/main/java/com/cvsgo/exception/product/DuplicateProductLikeException.java
  src/main/java/com/cvsgo/exception/product/NotFoundProductLikeException.java
  src/main/java/com/cvsgo/exception/product/ProductExceptionHandler.java
  src/main/java/com/cvsgo/repository/ProductLikeRepository.java
  src/main/java/com/cvsgo/repository/ProductRepository.java
  src/main/java/com/cvsgo/service/ProductService.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/com/cvsgo/controller/ProductControllerTest.java
  src/test/java/com/cvsgo/repository/ProductLikeRepositoryTest.java
  src/test/java/com/cvsgo/service/ProductServiceTest.java
Labels: feature

#34 상품 북마크 생성 / 삭제 기능 추가
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/cvsgo/config/WebConfig.java
  src/main/java/com/cvsgo/controller/ProductController.java
  src/main/java/com/cvsgo/entity/ProductBookmark.java
  src/main/java/com/cvsgo/exception/ErrorCode.java
  src/main/java/com/cvsgo/exception/ExceptionConstants.java
  src/main/java/com/cvsgo/exception/product/DuplicateProductBookmarkException.java
  src/main/java/com/cvsgo/exception/product/NotFoundProductBookmarkException.java
  src/main/java/com/cvsgo/exception/product/ProductExceptionHandler.java
  src/main/java/com/cvsgo/repository/ProductBookmarkRepository.java
  src/main/java/com/cvsgo/service/ProductService.java
  src/test/java/com/cvsgo/controller/ProductControllerTest.java
  src/test/java/com/cvsgo/repository/ProductBookmarkRepositoryTest.java
  src/test/java/com/cvsgo/repository/ProductRepositoryTest.java
  src/test/java/com/cvsgo/service/ProductServiceTest.java
Labels: feature

#35 리뷰 조회 기능 추가
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/cvsgo/controller/ReviewController.java
  src/main/java/com/cvsgo/dto/review/ReviewSortBy.java
  src/main/java/com/cvsgo/dto/review/SearchReviewQueryDto.java
  src/main/java/com/cvsgo/dto/review/SearchReviewRequestDto.java
  src/main/java/com/cvsgo/dto/review/SearchReviewResponseDto.java
  src/main/java/com/cvsgo/entity/Review.java
  src/main/java/com/cvsgo/entity/User.java
  src/main/java/com/cvsgo/repository/ReviewCustomRepository.java
  src/main/java/com/cvsgo/repository/ReviewCustomRepositoryImpl.java
  src/main/java/com/cvsgo/repository/ReviewImageRepository.java
  src/main/java/com/cvsgo/repository/ReviewRepository.java
  src/main/java/com/cvsgo/repository/UserTagRepository.java
  src/main/java/com/cvsgo/service/ReviewService.java
  src/main/resources/schema.sql
  src/test/java/com/cvsgo/controller/ReviewControllerTest.java
  src/test/java/com/cvsgo/service/ReviewServiceTest.java
Labels: feature

#38 sql 파일 수정
  sql/data.sql
  sql/schema.sql
Labels: chore
